### ISSUE TITLE
test.kak causes startup errors when placed in autoload

### ISSUE THREAD

**Issue by krobelus** [occivink/kakoune-interactive-itersel#7]
When cloning the entire repo in autoload (which is what plugin managers do), I get this error

```
>>>
/home/johannes/.config/kak/bundle/plugins/kakoune-phantom-selection/test.kak:1:1: 'try': 2:5: 'source': /home/johannes/git/kak-lsp/phantom-selection.kak: No such file or directory
bundle: couldn't source /home/johannes/.config/kak/bundle/plugins/kakoune-phantom-selection/test.kak
shell stderr: <<<
```

with this particular setup ("bundle" plugin manager), it leaves phantom-selection commands disfunctional.

Can we rename `test.kak` to something without the `kak` file extension, so it's not sourced automatically?

**Comment by occivink** [comment]
That's a bit unfortunate, as I've used this pattern in several repositories now. It's still a valid .kak file and I'd like to keep the name just to get the highlighting by default, but I also don't want to alienate plugin manager users for a trivial reason reason. 
I don't know how other repos address these, but I think there could be some kind of convention by plugin managers to ignore certain file names.

**Comment by krobelus** [comment]
our solution should work independent of a plugin manager. A `git clone` of a plugin into autoload should do the right thing.
I'm not sure if a way to ignore certain file names fits in Kakoune core.
There are myriad ways we could change `test.kak` to be a nop by default, like

```diff
diff --git a/test.kak b/test.kak
index 589cb59..0eaddc5 100644
--- a/test.kak
+++ b/test.kak
@@ -1,3 +1,5 @@
+provide-module phantom-selection-test %{
+
 try %{
     require-module phantom-selection
 } catch %{
@@ -49,3 +51,5 @@ phantom-selection-select-all
 assert-selections-are "'f'" 12
 
 delete-buffer
+
+}
```

**Comment by occivink** [comment]
I've now renamed the test file to `test.kak_`. It's not very elegant but good enough, and I don't want test files unnecessarily loaded by default.
